# Generated by Django 3.2 on 2021-12-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211221_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='cloth_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_sizes_man',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_sizes_woman',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
