# Generated by Django 3.2 on 2021-12-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211221_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cloth_sizes',
            new_name='cloth_size',
        ),
    ]
