# Generated by Django 3.2 on 2022-01-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_cloth_sizes_product_cloth_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
    ]
