# Generated by Django 3.2 on 2022-01-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=True, max_length=200, unique=True),
        ),
    ]
